spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MONEY_CALENDAR_DEV?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sung123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080